namespace PassouScanner.Domain.Data.SeedData;

/// <summary>
/// Marcas vendidas no Brasil, incluindo as que já saíram do mercado mas ainda circulam na frota
/// (ex: Troller, Gurgel, Kasinski). Referência: tabela FIPE.
/// </summary>
internal static class BrandSeedData
{
    public static readonly string[] CarBrands =
    [
        "Agrale",
        "Alfa Romeo",
        "Asia Motors",
        "Aston Martin",
        "Audi",
        "Bentley",
        "BMW",
        "BYD",
        "Caoa Chery",
        "Chery",
        "Chevrolet",
        "Chrysler",
        "Citroën",
        "Daewoo",
        "Daihatsu",
        "Dodge",
        "Effa",
        "Ferrari",
        "Fiat",
        "Ford",
        "GAC",
        "Geely",
        "Gurgel",
        "GWM",
        "Honda",
        "Hyundai",
        "Jac",
        "Jaecoo",
        "Jaguar",
        "Jeep",
        "Kia",
        "Lada",
        "Lamborghini",
        "Land Rover",
        "Leapmotor",
        "Lexus",
        "Lifan",
        "Maserati",
        "McLaren",
        "Mercedes-Benz",
        "Mini",
        "Mitsubishi",
        "Neta",
        "Nissan",
        "Omoda",
        "Peugeot",
        "Porsche",
        "Ram",
        "Renault",
        "Rolls-Royce",
        "Seat",
        "Smart",
        "SsangYong",
        "Subaru",
        "Suzuki",
        "Toyota",
        "Troller",
        "Volkswagen",
        "Volvo",
        "Zeekr",
    ];

    public static readonly string[] MotorcycleBrands =
    [
        "Aprilia",
        "Avelloz",
        "Bajaj",
        "Benelli",
        "BMW",
        "BRP",
        "CFMoto",
        "Dafra",
        "Ducati",
        "Haojue",
        "Harley-Davidson",
        "Honda",
        "Husqvarna",
        "Indian",
        "Kasinski",
        "Kawasaki",
        "KTM",
        "Kymco",
        "Mottu",
        "MV Agusta",
        "MXF",
        "Piaggio",
        "Royal Enfield",
        "Shineray",
        "Sundown",
        "Suzuki",
        "Traxx",
        "Triumph",
        "Vespa",
        "Voltz",
        "Yamaha",
        "Zontes",
    ];
}
